---

locale: en_US.UTF-8
user: user-data
user_home: /home/{{ user }}
user_db_path: "{{ user_home }}/mail/users.sqlite"
roundcube_db_path: "{{ user_home }}/mail/roundcube/roundcube.sqlite"


# TO CONFIGURE ===================
hostname: something.com
public_ip: 127.0.0.1

# Managing users =================
# Add commands to be run by mail.py (doc that later)
user_commands:
  - user add someone@{{ hostname }} password
  - alias add hostmaster@{{ hostname }} someone@{{ hostname }}
  - alias add postmaster@{{ hostname }} someone@{{ hostname }}

users:
  - someone@{{ hostname }}
