---

- name: Create nsd user
  user: name=nsd

- name: Install nsd
  apt: pkg=nsd state=present

- name: Create nsd directory
  file: path=/var/run/nsd state=directory

- name: Create dns directory in user home
  file: path={{ user_home }}/dns state=directory

- name: Create default zone
  file: path={{ user_home }}/dns/{{ hostname }}.txtit state=touch owner={{ user }} group={{ user }}

- name: Ensure the directory in home for dns is owned by the user
  file: path={{ user_home }}/dns state=directory owner={{ user }} group={{ user }}

- name: Permit DNS queries on TCP/UDP in the firewall
  shell: ufw allow domain

- name: Copy nsd conf
  template: src=nsd.conf.j2 dest=/etc/nsd/nsd.conf

- name: Create zones directory
  file: path=/etc/nsd/zones state=directory

- name: Copy zone config
  template: src=zone.txt.j2 dest=/etc/nsd/zones/{{ hostname }}.txt mode=0777 # todo find right perms
  notify:
    - restart nsd

- name: Append opendkim key to the zone
  shell: cat "{{ user_home }}/mail/dkim/mail.txt" >> /etc/nsd/zones/{{ hostname }}.txt;
  notify:
    - restart opendkim