---

- name: Install DKIM packages
  apt: pkg={{ item }} state=present
  with_items:
    - opendkim
    - opendkim-tools

- name: Create opendkim directories
  file: path=/etc/opendkim/keys state=directory recurse=yes

- name: Create TrustedHosts file
  copy: dest=/etc/opendkim/TrustedHosts content='127.0.0.1'

- name: Copy openDKIM conf
  copy: src=opendkim.conf dest=/etc/opendkim.conf

- name: Check whether we've already created a DKIM key
  command: /usr/bin/test -e /etc/opendkim/keys/mail.private
  register: has_dkim_key
  ignore_errors: True

- name: Create one if we didn't already
  shell: opendkim-genkey -r -s mail -D /etc/opendkim/keys -d {{ hostname }}
  when: has_dkim_key|failed

- name: Give correct permissions to opendkim keys
  file: path=/etc/opendkim/keys/{{ item }} mode=0600
  with_items:
    - mail.private
    - mail.txt

- name: Truncate OpenDKIM fles
  shell: truncate --size 0 {{ item }}
  with_items:
    - /etc/opendkim/KeyTable
    - /etc/opendkim/SigningTable

- name: Append a record to OpenDKIM's KeyTable
  shell: echo "{{ hostname }} {{ hostname }}:mail:/etc/opendkim/keys/mail.private" >> /etc/opendkim/KeyTable

- name: Append a record to OpenDKIM's SigningTable
  shell: echo "*@{{ hostname }} {{ hostname }}" >> /etc/opendkim/SigningTable

- name: Give correct permissions to opendkim folder/files in /etc
  file: path=/etc/opendkim/ owner=opendkim group=opendkim state=directory recurse=yes