---

- name: Install nginx and php
  apt: pkg={{ item }} state=present
  with_items:
    - nginx
    - php5-cgi

- name: Remove Apache
  apt: pkg=apache2 state=absent

- name: Remove default site-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/local.conf

- name: Copy nginx SSL config
  copy: src=nginx-ssl.conf dest=/etc/nginx/nginx-ssl.conf

- name: Copy custom init script for the PHP FastCGI daemon
  copy: src=php-fastcgi dest=/etc/init.d/php-fastcgi force=yes

- name: Keept it running after a reboot
  shell: update-rc.d php-fastcgi defaults

- name: Open firewall ports
  shell: ufw allow {{ item }}
  with_items:
    - http
    - https